site_name: Plataforma Lattes
repo_url: https://github.com/Interacao-Humano-Computador/2023.2-PlataformaLattes
repo_name: 2023.2-PlataformaLattes


theme:
  icon:
   repo: fontawesome/brands/git-alt
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: pt
  palette:
    - scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
      primary: teal
      accent: green
    - scheme: slate 
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode    
      primary: teal
      accent: blue